#pragma once

#include "glyph_atlas.h"

// GENERATED by glyph_atlas.py -- do not hand-edit.
// Per-glyph metrics for the Poiret One 14px 'ring' bitmap-glyph atlas
// (gabbro only -- see glyph_atlas.py's module docstring and font_report/
// for why this exists). Two atlas bitmaps share these metrics (white-fg
// and black-fg glyphs are pixel-identical except color, so they pack at
// the same coordinates).

#define GLYPH_ATLAS_RING_COUNT 15
// Empirically measured against native graphics_draw_text() -- see
// glyph_atlas.py's ATLASES comment. Added to bounds.origin.y before the
// tallest glyph's own bearing_y, so bitmap text lands at the same height
// native text would.
#define GLYPH_ATLAS_RING_Y_OFFSET 3

static const GlyphAtlasEntry GLYPH_ATLAS_RING[GLYPH_ATLAS_RING_COUNT] = {
  { '0', 0, 11, 11, 0, 11, 12 },
  { '1', 12, 2, 10, 0, 10, 4 },
  { '2', 15, 8, 11, 0, 11, 9 },
  { '3', 24, 8, 11, 0, 11, 8 },
  { '4', 33, 7, 11, 0, 11, 7 },
  { '5', 41, 8, 11, 0, 11, 9 },
  { '6', 50, 8, 11, 0, 11, 9 },
  { '7', 59, 7, 10, 0, 10, 8 },
  { '8', 67, 8, 11, 0, 11, 8 },
  { '9', 76, 8, 11, 0, 11, 9 },
  { '%', 85, 9, 11, 0, 11, 10 },
  { '-', 95, 4, 1, 0, 6, 6 },
  { ' ', 100, 0, 0, 0, 0, 5 },
  { '\xb0', 101, 2, 2, 0, 11, 3 },
  { ':', 104, 1, 5, 1, 4, 3 },
};

