#pragma once

#include "glyph_atlas.h"

// GENERATED by glyph_atlas.py -- do not hand-edit.
// Per-glyph metrics for the Poiret One 54px 'time' bitmap-glyph atlas
// (gabbro only -- see glyph_atlas.py's module docstring and font_report/
// for why this exists). Two atlas bitmaps share these metrics (white-fg
// and black-fg glyphs are pixel-identical except color, so they pack at
// the same coordinates).

#define GLYPH_ATLAS_TIME_COUNT 11
// Empirically measured against native graphics_draw_text() -- see
// glyph_atlas.py's ATLASES comment. Added to bounds.origin.y before the
// tallest glyph's own bearing_y, so bitmap text lands at the same height
// native text would.
#define GLYPH_ATLAS_TIME_Y_OFFSET 12

static const GlyphAtlasEntry GLYPH_ATLAS_TIME[GLYPH_ATLAS_TIME_COUNT] = {
  { '0', 0, 42, 42, 2, 41, 46 },
  { '1', 43, 8, 40, 1, 40, 13 },
  { '2', 52, 30, 41, 2, 41, 34 },
  { '3', 83, 28, 42, 2, 41, 32 },
  { '4', 112, 25, 41, 1, 41, 26 },
  { '5', 138, 30, 41, 2, 40, 35 },
  { '6', 169, 31, 41, 2, 40, 34 },
  { '7', 201, 27, 40, 1, 40, 29 },
  { '8', 229, 28, 42, 2, 41, 31 },
  { '9', 258, 31, 41, 2, 41, 34 },
  { ':', 290, 4, 18, 4, 18, 13 },
};

